modLoader = "lowcodefml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]] 
modId="spelunkery" 
version = "1.20.1-0.3.1"
displayName="Spelunkery" 
logoFile="icon.png" 
credits="Contributors: Bobisnotaperson, ElBones" 
authors="Ordana, Keybounce" 
itemIcon="spelunkery:rough_diamond" #catalogue icon
description='''
An Overhaul to everything Underground
'''

[[dependencies.spelunkery]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.spelunkery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

