modLoader = "lowcodefml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]]
modId = "spelunkery"
version = "1.20.1-0.1.2"
displayName = "Better Block Sounds"
displayURL = "https://discord.gg/MTUHt3r"
logoFile = "icon.png"
authors = "Ordana"
credits = "Inspired by Trainguy's Block Sounds Refresher."
description = "Block sounds, but better!"

[[dependencies.spelunkery]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.spelunkery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"