modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]] #mandatory

modId="bbs" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Better Block Sounds" #mandatory

logoFile="icon.png" #optional

credits="Based on concept and code by Trainguy" #optional

authors="Ordana, Trainguy" #optional

itemIcon="minecraft:music_disc_13" #catalogue icon

configuredBackground= "minecraft:textures/block/note_block.png"

description='''
Updating old blocks with new, better block sounds.
'''